# -*- coding: utf-8 -*-
"""Assignment, NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycpUcbtuf91oowMS7lhisaKwji1qcN5P
"""

import pandas as pd
import os
import zipfile

# ============================================================
# STEP 1: Extract the ZIP file
# ============================================================

ZIP_PATH = "/archive (2).zip"
DATA_DIR = "/home/claude/phishing_data"

# Create extraction folder
os.makedirs(DATA_DIR, exist_ok=True)

# Extract ZIP
with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(DATA_DIR)

print("ZIP extracted successfully!")
print("Files extracted to:", DATA_DIR)


# ============================================================
# STEP 2: Check extracted files
# ============================================================

print("\nExtracted files:")

for root, dirs, files in os.walk(DATA_DIR):
    for file in files:
        print(os.path.join(root, file))


# ============================================================
# STEP 3: Load raw datasets
# ============================================================

enron = pd.read_csv(os.path.join(DATA_DIR, "Enron.csv"))
ling = pd.read_csv(os.path.join(DATA_DIR, "Ling.csv"))
ceas = pd.read_csv(os.path.join(DATA_DIR, "CEAS_08.csv"))
nazario = pd.read_csv(os.path.join(DATA_DIR, "Nazario.csv"))
nigerian = pd.read_csv(os.path.join(DATA_DIR, "Nigerian_Fraud.csv"))
spamassassin = pd.read_csv(os.path.join(DATA_DIR, "SpamAssasin.csv"))


# ============================================================
# STEP 4: Show raw dataset shapes
# ============================================================

print("\nRaw shapes:")

for name, data in [
    ("Enron", enron),
    ("Ling", ling),
    ("CEAS", ceas),
    ("Nazario", nazario),
    ("Nigerian_Fraud", nigerian),
    ("SpamAssassin", spamassassin)
]:
    print(f"  {name}: {data.shape}")


# ============================================================
# STEP 5: Build mdf_1
# Enron + Ling
# Keep: subject, body, label
# ============================================================

mdf_1 = pd.concat([
    enron[["subject", "body", "label"]],
    ling[["subject", "body", "label"]]
], ignore_index=True)

# Handle missing values
mdf_1["subject"] = mdf_1["subject"].fillna("").astype(str)
mdf_1["body"] = mdf_1["body"].fillna("").astype(str)

# Combine subject + body
mdf_1["text_combined"] = (
    mdf_1["subject"] + " " + mdf_1["body"]
)

# Keep only required columns
mdf_1 = mdf_1[["text_combined", "label"]]

print("\nmdf_1 (Enron + Ling) shape:", mdf_1.shape)


# ============================================================
# STEP 6: Build mdf_2
# CEAS + Nazario + Nigerian Fraud + SpamAssassin
# ============================================================

cols = ["sender", "date", "subject", "body", "label"]

mdf_2 = pd.concat([
    ceas[cols],
    nazario[cols],
    nigerian[cols],
    spamassassin[cols]
], ignore_index=True)

# Handle missing values
for c in ["sender", "date", "subject", "body"]:
    mdf_2[c] = mdf_2[c].fillna("").astype(str)

# Combine email information
mdf_2["text_combined"] = (
    mdf_2["sender"] + " " +
    mdf_2["date"] + " " +
    mdf_2["subject"] + " " +
    mdf_2["body"]
)

# Keep only required columns
mdf_2 = mdf_2[["text_combined", "label"]]

print(
    "mdf_2 (CEAS + Nazario + Nigerian_Fraud + SpamAssassin) shape:",
    mdf_2.shape
)


# ============================================================
# STEP 7: Final merge
# ============================================================

final_df = pd.concat(
    [mdf_1, mdf_2],
    ignore_index=True
)

print("\nFinal merged dataset shape:", final_df.shape)


# ============================================================
# STEP 8: Label distribution
# ============================================================

print("\nLabel distribution:")
print(final_df["label"].value_counts())


# ============================================================
# STEP 9: Compare with paper
# ============================================================

print("\nExpected from paper:")
print("Total: 82,486")
print("Spam [1]: 42,891")
print("Ham [0]: 39,595")


# ============================================================
# STEP 10: Save final dataset
# ============================================================

OUTPUT_PATH = "/home/claude/merged_dataset.csv"

final_df.to_csv(
    OUTPUT_PATH,
    index=False
)

print("\nSaved successfully to:")
print(OUTPUT_PATH)

average="weighted"

import re
import string
import time
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

df = pd.read_csv("/home/claude/merged_dataset.csv")

import pandas as pd
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

df = pd.read_csv("/home/claude/merged_dataset.csv")

df = df.dropna(subset=["text_combined", "label"]).copy()

print("Dataset:", df.shape)
print(df["label"].value_counts())

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+|https\S+', ' ', text)
    text = re.sub(r'\S+@\S+', ' ', text)
    text = re.sub(r'<.*?>', ' ', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\d+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["clean_text"] = df["text_combined"].apply(clean_text)

print("Cleaning completed.")

X = df["clean_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF test shape :", X_test_tfidf.shape)

# =========================
# SVM
# =========================

print("Training SVM...")

svm_model = LinearSVC(
    C=1,
    random_state=42,
    max_iter=5000
)

svm_model.fit(X_train_tfidf, y_train)

y_pred_svm = svm_model.predict(X_test_tfidf)
svm_score = svm_model.decision_function(X_test_tfidf)

print("SVM completed.")

# =========================
# Multinomial Naive Bayes
# =========================

print("Training Multinomial Naive Bayes...")

nb_model = MultinomialNB(alpha=0.5)

nb_model.fit(X_train_tfidf, y_train)

y_pred_nb = nb_model.predict(X_test_tfidf)
nb_score = nb_model.predict_proba(X_test_tfidf)[:, 1]

print("Naive Bayes completed.")

# =========================
# Random Forest
# =========================

print("Training Random Forest...")

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=20,
    criterion="entropy",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_tfidf, y_train)

y_pred_rf = rf_model.predict(X_test_tfidf)
rf_score = rf_model.predict_proba(X_test_tfidf)[:, 1]

print("Random Forest completed.")

print("y_test:", y_test.shape)
print("SVM predictions:", y_pred_svm.shape)
print("NB predictions :", y_pred_nb.shape)
print("RF predictions :", y_pred_rf.shape)

print("=" * 70)
print("DETAILED CLASSIFICATION REPORTS")
print("=" * 70)

print("\n--- SVM ---")
print(classification_report(
    y_test,
    y_pred_svm,
    target_names=["Ham", "Phishing/Spam"]
))

print("\n--- Multinomial Naive Bayes ---")
print(classification_report(
    y_test,
    y_pred_nb,
    target_names=["Ham", "Phishing/Spam"]
))

print("\n--- Random Forest ---")
print(classification_report(
    y_test,
    y_pred_rf,
    target_names=["Ham", "Phishing/Spam"]
))

# ==========================================
# COMPARISON WITH PAPER'S REPORTED RESULTS
# ==========================================

import pandas as pd

# Your model results
our_results = {
    "SVM": {
        "Accuracy": accuracy_score(y_test, y_pred_svm) * 100,
        "Precision": precision_score(y_test, y_pred_svm, average="weighted") * 100,
        "Recall": recall_score(y_test, y_pred_svm, average="weighted") * 100,
        "F1-Score": f1_score(y_test, y_pred_svm, average="weighted") * 100,
        "AUC-ROC": roc_auc_score(y_test, svm_score) * 100
    },

    "Multinomial NB": {
        "Accuracy": accuracy_score(y_test, y_pred_nb) * 100,
        "Precision": precision_score(y_test, y_pred_nb, average="weighted") * 100,
        "Recall": recall_score(y_test, y_pred_nb, average="weighted") * 100,
        "F1-Score": f1_score(y_test, y_pred_nb, average="weighted") * 100,
        "AUC-ROC": roc_auc_score(y_test, nb_score) * 100
    },

    "Random Forest": {
        "Accuracy": accuracy_score(y_test, y_pred_rf) * 100,
        "Precision": precision_score(y_test, y_pred_rf, average="weighted") * 100,
        "Recall": recall_score(y_test, y_pred_rf, average="weighted") * 100,
        "F1-Score": f1_score(y_test, y_pred_rf, average="weighted") * 100,
        "AUC-ROC": roc_auc_score(y_test, rf_score) * 100
    }
}

our_df = pd.DataFrame(our_results).T

print("=" * 70)
print("OUR RESULTS")
print("=" * 70)
print(our_df.round(2))

paper_results = {
    "SVM": {
        "Accuracy": 99.19,
        "Precision": 99.00,
        "Recall": 99.00,
        "F1-Score": 99.00,
        "AUC-ROC": 99.19
    }
}

paper_df = pd.DataFrame(paper_results).T

print("\n" + "=" * 70)
print("PAPER RESULTS")
print("=" * 70)
print(paper_df.round(2))

# ==========================================
# DIFFERENCE: OUR RESULT - PAPER RESULT
# ==========================================

svm_comparison = pd.DataFrame({
    "Our SVM": our_df.loc["SVM"],
    "Paper SVM": paper_df.loc["SVM"]
})

svm_comparison["Difference"] = (
    svm_comparison["Our SVM"] -
    svm_comparison["Paper SVM"]
)

svm_comparison = svm_comparison.round(2)

print("\n" + "=" * 70)
print("SVM: OUR IMPLEMENTATION vs PAPER")
print("=" * 70)
print(svm_comparison)

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# ============================================================
# CONFUSION MATRICES
# ============================================================

# SVM
cm_svm = confusion_matrix(y_test, y_pred_svm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_svm,
    display_labels=["Ham", "Phishing/Spam"]
)

disp.plot()
plt.title("Confusion Matrix - SVM")
plt.show()


# Multinomial Naive Bayes
cm_nb = confusion_matrix(y_test, y_pred_nb)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_nb,
    display_labels=["Ham", "Phishing/Spam"]
)

disp.plot()
plt.title("Confusion Matrix - Multinomial Naive Bayes")
plt.show()


# Random Forest
cm_rf = confusion_matrix(y_test, y_pred_rf)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_rf,
    display_labels=["Ham", "Phishing/Spam"]
)

disp.plot()
plt.title("Confusion Matrix - Random Forest")
plt.show()

# ============================================================
# ROBUSTNESS EXPERIMENT
# ============================================================

import pandas as pd
import numpy as np
import re
import string

print("=" * 60)
print("ROBUSTNESS EXPERIMENT")
print("=" * 60)


# ------------------------------------------------------------
# 1. Select emails from the test set
# ------------------------------------------------------------

robustness_data = pd.DataFrame({
    "text": X_test.values,
    "actual_label": y_test.values
}).reset_index(drop=True)

# Use 500 test emails for the experiment
# Change to 1000 if your computer can handle it
robustness_data = robustness_data.sample(
    n=min(500, len(robustness_data)),
    random_state=42
).reset_index(drop=True)

print("Emails used:", len(robustness_data))


# ------------------------------------------------------------
# 2. Function for text cleaning
# ------------------------------------------------------------

def clean_robustness_text(text):

    text = str(text).lower()

    text = re.sub(
        r"http\S+|www\S+|https\S+",
        " ",
        text
    )

    text = re.sub(
        r"\S+@\S+",
        " ",
        text
    )

    text = re.sub(
        r"<.*?>",
        " ",
        text
    )

    text = text.translate(
        str.maketrans(
            "",
            "",
            string.punctuation
        )
    )

    text = re.sub(
        r"\d+",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# ------------------------------------------------------------
# 3. Create small text modifications
# ------------------------------------------------------------

def add_extra_spaces(text):

    return "  " + text.replace(" ", "   ") + "  "


def change_capitalization(text):

    words = text.split()

    changed = []

    for i, word in enumerate(words):

        if i % 3 == 0:
            changed.append(word.upper())

        else:
            changed.append(word)

    return " ".join(changed)


def add_harmless_words(text):

    return (
        "Please carefully review this message. "
        + text +
        " Thank you."
    )


# ------------------------------------------------------------
# 4. Create original and modified versions
# ------------------------------------------------------------

robustness_data["original"] = (
    robustness_data["text"]
    .apply(clean_robustness_text)
)

robustness_data["extra_spaces"] = (
    robustness_data["text"]
    .apply(add_extra_spaces)
    .apply(clean_robustness_text)
)

robustness_data["capitalization"] = (
    robustness_data["text"]
    .apply(change_capitalization)
    .apply(clean_robustness_text)
)

robustness_data["extra_words"] = (
    robustness_data["text"]
    .apply(add_harmless_words)
    .apply(clean_robustness_text)
)


# ------------------------------------------------------------
# 5. Prediction function
# ------------------------------------------------------------

def get_predictions(texts):

    tfidf_data = tfidf.transform(texts)

    svm_predictions = svm_model.predict(
        tfidf_data
    )

    nb_predictions = nb_model.predict(
        tfidf_data
    )

    rf_predictions = rf_model.predict(
        tfidf_data
    )

    return (
        svm_predictions,
        nb_predictions,
        rf_predictions
    )


# ------------------------------------------------------------
# 6. Get predictions for original emails
# ------------------------------------------------------------

(
    svm_original,
    nb_original,
    rf_original
) = get_predictions(
    robustness_data["original"]
)


# ------------------------------------------------------------
# 7. Get predictions for modified emails
# ------------------------------------------------------------

(
    svm_spaces,
    nb_spaces,
    rf_spaces
) = get_predictions(
    robustness_data["extra_spaces"]
)


(
    svm_caps,
    nb_caps,
    rf_caps
) = get_predictions(
    robustness_data["capitalization"]
)


(
    svm_words,
    nb_words,
    rf_words
) = get_predictions(
    robustness_data["extra_words"]
)


# ------------------------------------------------------------
# 8. Calculate prediction consistency
# ------------------------------------------------------------

def consistency(original, modified):

    return np.mean(
        original == modified
    ) * 100


robustness_results = {

    "SVM": {

        "Extra Spaces":
            consistency(
                svm_original,
                svm_spaces
            ),

        "Capitalization":
            consistency(
                svm_original,
                svm_caps
            ),

        "Extra Words":
            consistency(
                svm_original,
                svm_words
            )
    },

    "Multinomial Naive Bayes": {

        "Extra Spaces":
            consistency(
                nb_original,
                nb_spaces
            ),

        "Capitalization":
            consistency(
                nb_original,
                nb_caps
            ),

        "Extra Words":
            consistency(
                nb_original,
                nb_words
            )
    },

    "Random Forest": {

        "Extra Spaces":
            consistency(
                rf_original,
                rf_spaces
            ),

        "Capitalization":
            consistency(
                rf_original,
                rf_caps
            ),

        "Extra Words":
            consistency(
                rf_original,
                rf_words
            )
    }
}


# ------------------------------------------------------------
# 9. Display robustness results
# ------------------------------------------------------------

robustness_df = pd.DataFrame(
    robustness_results
).T

robustness_df = robustness_df.round(2)

print("\n")
print("=" * 60)
print("ROBUSTNESS RESULTS (%)")
print("=" * 60)

print(robustness_df)


# ------------------------------------------------------------
# 10. Average robustness score
# ------------------------------------------------------------

robustness_df["Average Consistency"] = (
    robustness_df.mean(axis=1)
).round(2)

print("\n")
print("=" * 60)
print("AVERAGE ROBUSTNESS")
print("=" * 60)

print(
    robustness_df[
        ["Average Consistency"]
    ]
)


# ------------------------------------------------------------
# 11. Save results
# ------------------------------------------------------------

robustness_df.to_csv(
    "/home/claude/robustness_results.csv"
)

print(
    "\nRobustness results saved to:"
)

print(
    "/home/claude/robustness_results.csv"
)

